#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running commit message lint..."

# Xác định package manager
if [ -f yarn.lock ]; then
  PM="yarn"
elif [ -f pnpm-lock.yaml ]; then
  PM="pnpm"
elif [ -f package-lock.json ]; then
  PM="npm"
else
  echo "❌ No recognized package manager lock file found!"
  exit 1
fi

# Lint commit message
npx --no -- commitlint --edit "$1"

# Nếu cần có thể format + lint lại code luôn ở đây
if [ "$PM" = "npm" ]; then
  npm run lint:fix && npm run format:fix
else
  $PM lint:fix && $PM format:fix
fi
